spring:
  profiles:
    include:
      - db
      - jwt
      - smtp
      - swagger
      - redis
      - oauth
  mvc:
    hidden-method:
      filter:
        enabled: true

cors:
  allowed-origins:
    - http://localhost:8080
    - http://localhost:3000
    - http://kakaoscan.com
    - https://kakaoscan.com
  permit-all-endpoints:
    - /
    - /api/verify/**
    - /api/login/**
    - /api/register
    - /api/logout
    - /api/refresh-token
    - /swagger-ui/**
    - /v3/api-docs/**
    - /index.html
    - /static/**
    - /favicon.png
    - /ws/**