spring:
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      port: 6379

---

spring:
  config:
      activate:
        on-profile: dev
  data:
    redis:
      host: localhost #host.docker.internal

---

spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: redis #${REDIS_HOST}
      password: ${REDIS_PASSWORD}