spring:
  config:
    import:
      - classpath:application-redis.yml
      - classpath:application-jwt.yml
      - classpath:application-smtp.yml
      - classpath:application-swagger.yml
      - classpath:application-words.yml
      - classpath:application-private.yml

  mvc:
    hidden-method:
      filter:
        enabled: true

cors:
  allowed-origins:
    - http://localhost:8080
    - http://localhost:3000
    - http://kakaoscan.com
    - https://kakaoscan.com
    - http://test.kakaoscan.com
    - https://test.kakaoscan.com
  permit-all-endpoints:
    - /
    - /api/verify/**
    - /api/login/**
    - /api/register
    - /api/refresh-token
    - /swagger-ui/**
    - /v3/api-docs/**
    - /index.html
    - /static/**
    - /favicon.png
    - /ws/**

---

spring:
  config:
    activate:
      on-profile: dev, test

verify:
  prefix: http://localhost:8080/api/verify/
  replace: http://localhost:3000

search:
  profile:
    cost:
      origin: 500
      discount: 250

---

spring:
  config:
    activate:
      on-profile: prod

verify:
  prefix: ${CURRENT_BASE_URL}/api/verify/
  replace: ${CURRENT_BASE_URL}

search:
  profile:
    cost:
      origin: 500
      discount: 250