words:
  adjectives:
    - 푸른
    - 좋은
    - 나쁜
    - 큰
    - 작은
    - 높은
    - 낮은
    - 빠른
    - 느린
    - 많은
    - 적은
    - 얇은
    - 추운
    - 밝은
    - 상한
    - 달콤
    - 매운
    - 깊은
    - 넓은
    - 좁은
    - 놀란
    - 젊은
    - 늙은
    - 슬픈
    - 멋진
    - 진한
    - 급한
    - 흐린
    - 맑은
    - 고른
    - 낡은
    - 서툰
  nouns:
    - 사람
    - 나무
    - 바다
    - 책
    - 차
    - 집
    - 학교
    - 공원
    - 도시
    - 산
    - 강
    - 하늘
    - 구름
    - 비
    - 눈
    - 꽃
    - 풀
    - 새
    - 쥐
    - 소
    - 말
    - 돼지
    - 새우
    - 곰
    - 사슴
    - 여우
    - 밤
    - 낮
    - 별
    - 달
    - 태양
    - 바람
    - 불
    - 땅
    - 모래
    - 돌
    - 섬
    - 물
    - 얼음
    - 연기
    - 구멍
    - 길
    - 다리
    - 문
    - 창
    - 벽
    - 천장
    - 바닥
    - 계단
    - 소리
    - 노래
    - 그림
    - 사진
    - 음식
    - 음료
    - 과일
    - 채소
    - 고기
    - 빵
    - 딸기
    - 과자
    - 사과
    - 커피
    - 차
    - 주스