spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

logging:
  level:
    org:
      hibernate: # SQL 쿼리 로그 레벨 설정
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
