spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
